### ISSUE TITLE
Cannot load this module

### ISSUE THREAD

**Issue by rohitsoni77** [eouia/MMM-CalendarExt#1]
On adding this module in config.js and trying to start , I get the error 

[SyntaxError: Unexpected token =]

Is it a known issue?

**Comment by eouia** [comment]
Give me more detailed information please.
Can you post your `MMM-CalendarExt` section in config.js?
And tell me which file and line the error is occurred in.

**Comment by eouia** [comment]
Is there any issue about this?

**Comment by eouia** [comment]
I'll close this because of no further action.

**Comment by rohitsoni77** [comment]
I have declared the following configuration:

{
    module: 'MMM-CalendarExt',
    header: 'Calendar',
    position: "top_left", //anywhere. It is not related to real position of view
    config: { // Read below
          defaultView: {
            position: 'bottom_bar',
              positionOrder: -1,
                overflowRolling: 0,
                  overflowHeight: 0,
                    overflowDuration: 2,
                      timeFormat: 'HH:mm',
                        dateFormat: "MMM Do",
                          fullDayEventDateFormat: "MMM Do",
                            ellipsis: 0,
                              limit:0,
                                oneLineEvent:0,
                                  replaceTitle:[],
                                    classPattern:[],
                                      classPatternWhere:["title"]
                                      },
          calendars: [
                          {
                              url: "mycalendar.ics",
                               view: ['month', 'upcoming'],
                                   styleName: "style1",
                                       symbol: 'us@fi',
                                           maxEntries: 50,
                                               maxDays:365,
                                                   interval: 24*60*60*1000,
                                                   name: 'My calendar'
                           }
                      ]
           }

 }

But when I try to start the magic mirror , it throws config error and when I change the name of the module from MMM-CalendarExt to CalendarExt or anything else , it starts, but even after starting it shows blank screen ,the error seen in the Chrome developer tools is :

loader.js:190 Error on loading script: modules/CalendarExt//CalendarExt.js

Not sure why its not loading with name MMM-CalendarExt , the error while starting is :

WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
Loading module helpers ...
Whoops! There was an uncaught exception...
[SyntaxError: Unexpected token =]
