### ISSUE TITLE
Can't have two calendar modules at the same time?

### ISSUE THREAD

**Issue by SebastianFalborg** [eouia/MMM-CalendarExt#12]
I wanted to use two of this module at the same time, but if I try (and I have checked that I have them at different positions), then they don't load at all.
They both show separately.

**Comment by eouia** [comment]
Two instances are not allowed. Why do you need that? (What is your real intention?)
If I know the reason, I can suggest better answer or suggestions.

**Comment by eouia** [comment]
What you mean is just displaying several calendars at sme time, just add calendars in `calendars`.
See https://github.com/eouia/MMM-CalendarExt/wiki/Configuration#calendars

**Comment by SebastianFalborg** [comment]
I wanted something like this. With two calendars separate with its own daily view.
I wanted it to be like a school schedule (Monday to friday) with the whole school schedule displayed for that week.
This is what I am trying to do.

![magicmirror](https://user-images.githubusercontent.com/6458892/30899531-82023b1c-a360-11e7-8a7f-af2f7359356b.PNG)

If it isn't possible I'll try myself :)

**Comment by eouia** [comment]
@iSoap Ok. Now I understand your intention.
Unfortunately, MagicMirror doesn't allow to run multi node_helper of a module. Every instance of the specific module SHOULD SHARE the same node_helper. Frankly, that's the reason why I build this module. But I've never imagined who needs multi-daily views. :)

Now, we can consider some options.
1) Just combine two calendars. - But you seem not to want this.
2) Using profiles. You can show events by profile. It means you can switch 2 calendars in a same daily view, but not simultaneously.
3) Fork this source and modify your own.
If you need 2 daily views at the same time, I think some modification is needed.
I believe it's not so difficult to add additional daily view. The only problem is... that's not a universal purpose. So I have some hesitation for doing that by myself.

**Comment by eouia** [comment]
Ah, the easist way could be to rename module.

**Comment by SebastianFalborg** [comment]
I have tried to make a new folder called MMM-CalendarExt2 with the other module. Do I need to rename anything in the new folder?

**Comment by eouia** [comment]
Rename MMM-CalendarExt.js
and
in MMM-CalendarExt.js,
```
Module.register("MMM-CalendarExt", { 
```
Modify this. I think that is enough.

Additionally,  CSS could be confused. remove CSS contents and leave blank (in .css) of the renamed module.

**Comment by eouia** [comment]
In this case, CSS could be confused. remove CSS contents(in .css) of the renamed module.

**Comment by eouia** [comment]
Sorry for saying this.
I tried to rename module, but it is more complex than I've thought.
It's not easy to run 2 modules together.

**Comment by SebastianFalborg** [comment]
I have made a new folder called MMM-CalendarExt2 put a copy into it, I have renamed the file to MMM-CalendarExt2.js and renamed it MMM-CalendarExt2 in the Module.register.
Despite having two separate in config.js with one being MMM-CalendarExt and one called MMM-CalendarExt2.
They can still only show one or the other.
Btw. Thank you for your responses.
If I remove the "custom.css" in the renamed module. It doesn't format at all, so I think it is reading its own .css.

**Comment by SebastianFalborg** [comment]
Oh sorry. I didn't see you wrote. Had forgotten to refresh the page. I might just add them in the same calendar. It's just a little confusing. Thanks for all your replies. :)

**Comment by SebastianFalborg** [comment]
If I add two calendars in one. Can I make sure (if they start at the same time like 9:45), that one always is shown first?

**Comment by eouia** [comment]
@iSoap 
I'd considered those kinds of sorting order ago. but currently not supported.

The current sorting order is;
1) FulldayEvents
2) Start Time 

I think you can modify that here 
https://github.com/eouia/MMM-CalendarExt/blob/master/Render.js#L585

**Comment by eouia** [comment]
@iSoap I added the another sorting filter by name. 
Now your calendar `a` will be upper than calendar `b` when the start time is same.

**Comment by eouia** [comment]
I'll close this issue.
