### ISSUE TITLE
Question: Symbol in classPattern?

### ISSUE THREAD

**Issue by TNT911** [eouia/MMM-CalendarExt#13]
If there a way to assign symbols to events using classPattern?  If not, might I recommend this.
I have a 1 calendar with multiple sport events.  Hockey, Baseball, Soccer etc.   It would be nice to assign symbols to etc type of sport.
TIA!  Keep up the great work on this module.

**Comment by eouia** [comment]
Not supported but i consider to implement next.

**Comment by TNT911** [comment]
Awesome!  Keep up the great work.

**Comment by eouia** [comment]
I add `symbolPattern` and `symbolPatternWhere` in `view` and `calendar`.
Please test and report me.
(unlike classPattern, symbol will be overwritten by last matched pattern)

**Comment by TNT911** [comment]
OMG So awesome!  Will do.

**Comment by eouia** [comment]
Is there any problem? I'll close this issue.

**Comment by TNT911** [comment]
Everything works fine. Thank you
