### ISSUE TITLE
Provide config.js files for examples

### ISSUE THREAD

**Issue by rgstephens** [eouia/MMM-CalendarExt#19]
It would be great to have the config.js files for your examples.  I'm having basic problems with positioning of the calendar on the screen.  If you could provide all of your great examples as separate config.js files in an examples directory, that would be very helpful.

**Comment by eouia** [comment]
I'll provide sample config.js after a few days. I'm on vacation of holiday seasons. Happy new year!

**Comment by Joshua2504** [comment]
Push!

**Comment by eouia** [comment]
Sorry for my late answer. I was out for some long while.
See https://github.com/eouia/MMM-CalendarExt/wiki/Configuration#too-difficult
