### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by MichiMich** [eouia/MMM-CalendarExt#2]
Hello there,

i cloned your repository as mentioned and used the default config:

  module: 'MMM-CalendarExt',
  position: "top_left",
  config: {
    calendars: [
      {
        url: "mycalendar.ics"
      }
    ]
  }
},

But if i start the Mirror there is nothing displayed. I only get a black window. Did you notice this error?

Best regards 

Michael

**Comment by eouia** [comment]
When I test it again now, I cannot find any problem.

Could you test your `MagicMirror` with `debug` mode?
Or you can do this.
```
cd ~/MagicMirror
node serveronly
```
After that, you can see log for node_helpers on your terminal. Is there any suspicious error messages?
Then, open your browser(Chrome) and navigate to `localhost:8080`. Is the mirror is still black?
Then, Select the Chrome menu at the top-right of your browser window, then select Tools > Developer Tools. Then you can see additional window on left or below side of `MM`. Go to `Console` tab. Is there any suspicious error message?

**Comment by eouia** [comment]
Ah.. you are Mich.^^;;;
Ok, you are familiar with your mirror. So, is there any problem in my module? I believe you can check the errors.

**Comment by MichiMich** [comment]
Ok i figured out the problem. I used your module in the module "MMM-Carousel w/ Slide Navigation" (https://github.com/shbatm/MMM-Carousel) from @shbatm .  If I set the MMM-CalendarExt module as 1st will work, but if i set it as a slide later (2nd, 3rd, 4th...) it will not work. Here is my configuration which works:

```
{
	module: 'MMM-Carousel',
	position: "bottom_bar",	
            config: {
                transitionInterval: 0,
		showPageIndicators: false,
		ignoreModules: ['clock', 'alert'],
                mode: 'slides',
                slides: [
			['MMM-CalendarExt'],
                    	['calendar', 'compliments', 'currentweather', 'weatherforecast'],
			['calendar_monthly'],
			['MMM-Traffic', 'newsfeed'],
			['phone-notification', 'email']
			//['MMM-Button', 'MMM-Podcast']
                ],
		keyBindingsMode: "DEFAULT",
                keyBindings: { 
                    NextSlide: "ArrowRight", 
                    PrevSlide: "ArrowLeft", 
                    Slide0:    "Home"
                }
            }
        },
```
And here is a configuration which does not display the MMM-CalendarExt module. Note that the configuration should be right.
```
{
	module: 'MMM-Carousel',
	position: "bottom_bar",	
            config: {
                transitionInterval: 0,
		showPageIndicators: false,
		ignoreModules: ['clock', 'alert'],
                mode: 'slides',
                slides: [
                    	['calendar', 'compliments', 'currentweather', 'weatherforecast'],
			['calendar_monthly'],
			['MMM-CalendarExt'],
			['MMM-Traffic', 'newsfeed'],
			['phone-notification', 'email']
			//['MMM-Button', 'MMM-Podcast']
                ],
		keyBindingsMode: "DEFAULT",
                keyBindings: { 
                    NextSlide: "ArrowRight", 
                    PrevSlide: "ArrowLeft", 
                    Slide0:    "Home"
                }
            }
        },
```

So for me this works, because i can set the MMM-CalendarExt module at 1st slide...maybe someone can figure out whats the problem here...

Thanks for your help. Appreciate that

**Comment by eouia** [comment]
Good.
I didn't test Mmm-carousel. Anyway, there is possibility of problem with that module. Because calendarext uses hooking hide-show mechanism, so other module which controls hide-show could make collison. 
Anyway you've found solution, congratulation!

**Comment by eouia** [comment]
I'll close this issue.
