### ISSUE TITLE
Calendar isn´t showing after latest MM update

### ISSUE THREAD

**Issue by PhilippTh** [eouia/MMM-CalendarExt#21]
Hey eouia!

Thirst of all, thanks a lot for the awesome work, if been enjoying your module a lot so far.

My problem is, that since I updated MM to the latest version of the master branch today, I can´t seem to get your calendar to work again.

Things I´ve tried:
-Starting MM with dev didn´t give me any errors but the calendar was of course still not showing.
-I backed up the small changes I made to your repository and downloaded it again. Nothing changed
-I deleted the config.js entry for your calendar and added the simple one you suggest at the end of your wiki page about configuration. Unfortunately to no avail.

I´d be very thankful if you could help me troubleshoot this problem.
Are any other users experiencing the same issue?

Thanks and kind regards!
Phil

**Comment by eouia** [comment]
I doubt MM has downgraded its node version of electron for some reason.
Unfortunately, ‘async function’ is not working on the lower version of node. I think that is the reason for this issue.
I’ll check and patch this for some time. Sorry, I should do my job first before this. Plz wait for a while.

**Comment by PhilippTh** [comment]
Of course, no worries!

**Comment by ninjabreadman** [comment]
Not ideal, but you can enable async with flags: https://forum.magicmirror.builders/topic/6047/calendar-module-won-t-show-all-events/4

**Comment by eouia** [comment]
I removed `async` from source. I hope this could be the solution.
