### ISSUE TITLE
Add eventDescription as displayable element

### ISSUE THREAD

**Issue by easyas314** [eouia/MMM-CalendarExt#22]
Happy New Year! Thanks for the great extension! Trying to understand all the options.  ;-)
Instead of event locations, I am more interested in event descriptions. Could you add an option to include event description in the display of an event? Maybe with it's own style?

**Comment by eouia** [comment]
```
.CALEXT .eventLocation {
    text-align:right;
    font-size:80%;
    font-weight:normal;
    order:4;
}

.CALEXT .eventDescription {
  order:3;
  display:none;
}
```
That was hidden by this script in `MMM-CalendarExt/custom.css`. You can modify this or add your own styles to your main `custom.css`(recommended) if you know something about CSS.
