### ISSUE TITLE
Display start time for Event in weeks or month Mode

### ISSUE THREAD

**Issue by GerPrimus** [eouia/MMM-CalendarExt#27]
Hello everyone,
i´m looking for a way do display the start time for an event in weeks-mode.
i´ve be looking through "custom.css" but only could find:

`.CALEXT .weeks .fulldayevent .eventTime,`
`.CALEXT .month .fulldayevent .eventTime,`
`.CALEXT .daily .fulldayevent .eventTime {`
    `display:none;`
`}`

is this the right one? am i missing something?

Thanks,
F

**Comment by eouia** [comment]
@GerPrimus 
Here you should modify.
```
.CALEXT .tableStyle .eventLocation,
.CALEXT .tableStyle .eventTime {
    display:none;
}
```

**Comment by GerPrimus** [comment]
@eouia 
Wow, thanks for the quick awnser!
Found it, but is there a way to show only the start time, not location, etc?
im sorry, my CSS is not the best... :-D

**Comment by eouia** [comment]
```
.CALEXT .tableStyle .eventLocation {
     display:none;
}
.CALEXT .tableStyle .eventTime {
    display:block;
}
```

**Comment by GerPrimus** [comment]
Thank you! Thats it. 👍

**Comment by sworrs** [comment]
Hi,
I used the change you wrote in custom.css but it did change anything. Is there anything I have to do except change
.CALEXT .tableStyle .eventLocation,
.CALEXT .tableStyle .eventTime {
    display:none;
}
to 
.CALEXT .tableStyle .eventLocation {
     display:none;
}
.CALEXT .tableStyle .eventTime {
    display:block;
}

Thanks in advance

**Comment by sworrs** [comment]
Sorry, I found the problem. You depricated the custom.css. After editing the MMM-CalendarExt.css it worked.
Thank you

**Comment by eouia** [comment]
Nice to you. I’ll close this issue.
