### ISSUE TITLE
Complete sample DOM for styles

### ISSUE THREAD

**Issue by jtuckr** [eouia/MMM-CalendarExt#28]
I know you have some snippets of the DOM for each event and slot in the wiki, but I was wondering if you could include a complete sample DOM from the wrapper all the way down (ideally for each of the 7 view types) so I could recreate the layout and test out styling changes on it with custom.css?

**Comment by eouia** [comment]
Sorry, I have not enough time for that currently.(I should do my real job for nowadays) If I could, it would be a month or later.
I believe you can get whole the structure (and variation) by yourself with running MM on development environments like PC and Chrome or Firefox.

**Comment by jtuckr** [comment]
I was able to get through it by running magic mirror server only and opening the magic mirror page in Chromium so I could use Chrome Dev Tools. Thanks for the great module!
