### ISSUE TITLE
Seek  for css class

### ISSUE THREAD

**Issue by landaisbenj** [eouia/MMM-CalendarExt#30]
Hello. 

I've do some change on my look but and don't find how change color of day's font. Someone can help me ?

A map with all class could be great...

I want to change this:
![image](https://user-images.githubusercontent.com/32144431/38485364-be8f556c-3bd9-11e8-833e-7f95e8c47c01.png)

And if you know, how make a fixed height of empty weeks and why my titlemonth have no caps on first letter, i take too...

**Comment by fenixjr** [comment]
```
.CALEXT .weeks th{
    width:100px;
    font-weight:normal;
    font-size:50%;
    color: #FFF
```

Just add that color line to the css and change to what you want. i think that should do it for you

**Comment by landaisbenj** [comment]
Hello. Thanks for your reply. 

But don't work. I put screen tomorrow

**Comment by landaisbenj** [comment]
I've this 


.CALEXT .weeks th{
    width:100px;
    font-weight:normal;
    font-size:50%;
    color:#FFF;
}

.CALEXT .weeks th {
    width:100px;
    color:#FFF;
}

**Comment by landaisbenj** [comment]
It's the default css...

**Comment by fenixjr** [comment]
oh sorry. i'm on the "weeks" view (looks so similar i didnt notice), so it did it when i tested.

**Comment by fenixjr** [comment]
```
.CALEXT .month th{
    width:100px;
    font-weight:normal;
    font-size:50%;
	color: #FFF
}
```

Tested with that added and worked

**Comment by landaisbenj** [comment]
Okkk it's work really great!!! Really thanks. It's not implemented on default custom.css.

**Comment by landaisbenj** [comment]
Hello unfortunatly this make me white in number of week too... I don't want this because i make a white just on thisweek number... Do you have a solution ?
