### ISSUE TITLE
Witdh 100%?

### ISSUE THREAD

**Issue by landaisbenj** [eouia/MMM-CalendarExt#32]
Hello. 

I have this board:
![image](https://user-images.githubusercontent.com/32144431/38772982-6bd75748-4043-11e8-9636-0ec5195596c4.png)
Do you know, how can i make ma calendar more large ?

**Comment by fenixjr** [comment]
```
 .CALEXT .tableStyle {
     margin: -50px;
     max-width: 150%;
 }
 
```

I changed my CSS to something like that. worked well. might need some fine tuning.

**Comment by landaisbenj** [comment]
Thank you!!!!

Work fine with this:

'''
margin:0px;
max-width: 100%;
'''
