### ISSUE TITLE
Change the first day of the week

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt#34]
Is there a way to change the first day of the week from Sunday to Monday?
I would like the calendar to begin with Monday.

**Comment by eouia** [comment]
It depends on which locale you are under. Change locale to your purpose.

**Comment by eouia** [comment]
Monday is the first day of the week according to the international standard ISO 8601, but in the US, Canada, and Japan it's counted as the second day of the week.
So, If you are using `en-US` as locale, Sunday will be the first day of the week.
If you are using `en-GB` as locale, Monday will be the first day of the week.

**Comment by ingo916** [comment]
Thank you!!! the local en-GB work  the way i needed it to.

**Comment by gidimiz** [comment]
Hi. How can I set my work week from Sunday and Friday & Saturday off? 
I tried using ( [https://momentjs.com/](url) ) English ( Israel) 
`system: {
locale: "en-il"
},`
and its not changing.
