### ISSUE TITLE
Add separation between the current week and following week

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt#35]
Is it possible to add separation between the current week and following week when the calendar is displayed in weeks? I would like to add some space between the bottom and top of the calendars see attached image with red arrow mark.
"system": {
	"show": ["weeks"]
![2018-07-16_15-39-05](https://user-images.githubusercontent.com/41309095/42787392-2a4c34be-890f-11e8-8fd6-cf3148a25939.jpg)

**Comment by eouia** [comment]
Not tested, but I think modifying CSS rule of class name ”thisweek” might work.

**Comment by eouia** [comment]
Are, you just put the "space", not "border"... Hmmm.. the html structure is `table` so It cannot be separated physically. but what you want is giving attentional look to this week, you can add more decoration.
Try this code in your `custom.css` (not tested but you can get an idea)
```css
.CALEXT  tr.thisweek td {
    border-bottom: 2px solid #FFF;
}
```

**Comment by ingo916** [comment]
Thanks!! the code you recommended works perfectly.
