### ISSUE TITLE
Calendar icons

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt#36]
I am trying to change the icons for specific calendars. I have 6 total and was able to change one using the following code `"symbol": "user-secret@fa",` in config.js But when i add a different one for another calendar it doesnt show up or no icon appears. this screen shot shows it wortking with one calendar, the second shows two calendars configured to use two different icons

![2018-07-20_13-49-03](https://user-images.githubusercontent.com/41309095/43024867-78cd971e-8c24-11e8-84cb-67653d0c17ef.jpg)
![2018-07-20_14-00-37](https://user-images.githubusercontent.com/41309095/43025153-8660c79c-8c25-11e8-89ec-3a900d3ee385.jpg)

Here is the code for my config.js
`				"calendars": [
					{
						"name": "Ingo&Jen",
						"symbol": "user-friends@fa",
						"styleName": "style2",
						"url": "Calendar link here"
					},
					{
						"name": "US Holiday",
						"url": "Calendar link here",
						"symbol": "us@fi",
						"styleName": "style6",
						"interval": 24*60*60*1000,
						"maxEntries": 50,
						"maxDays":365,
					},
					{
//						"name": "",
						"symbol": "calendar",
						"styleName": "style3",
						"url": "Calendar link here",
					},
					{
//						"name": "",
						"symbol": "calendar",
						"styleName": "style4",
						"url": "Calendar link here",
					},
					{
//						"name": "",
						"symbol": "calendar",
						"styleName": "style5",
						"url": "Calendar link here",
					},
					{
						"name": "Ingo RCPD",
						"symbol": "user-secret@fa",
						"styleName": "style1",
						"url": "Calendar link here",
						"interval": 24*60*60*1000,
					},
				],`

**Comment by eouia** [comment]
Default MagicMirror's `font-awesome` has version 4.7. But your `user-friends` is added on V5.0. That is why your icon is not shown.
