### ISSUE TITLE
authentication of calendar 

### ISSUE THREAD

**Issue by slodub** [eouia/MMM-CalendarExt#38]
I'm struggling to get a calendar to show that requires login. I know user and password, but am unsure what 'method' is used for and what options for that field. Thanks

**Comment by eouia** [comment]
Usually, it would be "basic" or "bearer". But I should know exact information about which calendar you want to use.

```
calendars: [
  {
    name: "Schooldays of John",
    url: "https://school.com/schedule.ics",
    auth: {
      user:'john',
      pass:'abcd1234',
      method:'bearer'
    }
  },
...
],
```

**Comment by slodub** [comment]
I have several calendars loaded and working, this one is the Google Family calendar. The calendar is private, and I'm using the provide public link from settings. When I paste the link into a private browser window (to not have my account signed in) I am directed to sign in. So I am trying to use auth in my config.js. I tried both 'bearer' and 'basic' with no success. I have read that this calendar is created when a family account is setup and it can't be imported to other things like outlook due to being forced private, but I was hoping I could use it here in MM ..

**Comment by eouia** [comment]
As I know, Google Family calendar is not able to be exported outside from Google. Sorry.

**Comment by eouia** [comment]
I'll close this issue. Good luck to you.
