### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by nightshocker** [eouia/MMM-CalendarExt#43]
Hey All,
How do I update I have looked here and on the MagicMirror mmm-calendarext subfourm but can not find it.

Also how do i disable the modular so that it still shows my calendar even if I do not update. I think it should still work even with out updating it. why fully disable it because there is an update?

Thanks in advance.

**Comment by eouia** [comment]
- For update;
```
cd ~/MagicMirror/modules/MMM-CalendarExt
git pull
```

- For disabling update notification
Go to your configuration(`config.js`) then;
```
{
  disabled: true, // add this line or remove whole section.
  module: "updatenotification",
  position: "top_bar"
},
```

**Comment by nightshocker** [comment]
wow thank you for the quick reply.

**Comment by eouia** [comment]
I’ll close this issue. Have a nice time.
