### ISSUE TITLE
Events with start time show as full day event

### ISSUE THREAD

**Issue by slodub** [eouia/MMM-CalendarExt#44]
Is there anyway to get an event that only has a start time to not show up as an all day event?

**Comment by eouia** [comment]
Obvious question. 
All day event - Starts from 00:00AM and ends in 24:00PM(of any day). So, start & end time is meaningless.
Which case did you mean? give me the example.

**Comment by slodub** [comment]
The event has a start time but end time. See attached picture for events on
10/6 & 10/7...

Here is the calendar link to test:
webcal://www.cheektowagawarriors.net/ical_feed?tags=4108079

Nick

**Comment by eouia** [comment]
So, you just want to display "Peewee Minor Red - Early Bird Tournament" event on only 10/6 not on 10/7? Sorry, in that case, impossible. That event is 2-days all day event, and this module isn't made for that purpose.
Only in `upcoming` and `current` view, you can show start time.

**Comment by slodub** [comment]
No I am ok with the full day event showing on both days. 
There is a second event on 10/6 from that calendar "Batavia at Peewee Minor Red" with a start time of 4:00pm, but no end time. In month view which is my primary view that event shows as an all day event also.

**Comment by eouia** [comment]
I've fixed. try it.

**Comment by slodub** [comment]
I'll try shortly, thanks!

**Comment by eouia** [comment]
I'll close this.
