### ISSUE TITLE
custom.css doesn't seem to work

### ISSUE THREAD

**Issue by dberntsson** [eouia/MMM-CalendarExt#45]
I have made the following addition to MMM-CalendarExt/custom.css

pi@raspberrypi:~/MagicMirror/modules/MMM-CalendarExt $ git diff
diff --git a/custom.css b/custom.css
index 58b01e7..bbb683c 100644
--- a/custom.css
+++ b/custom.css
@@ -158,8 +158,12 @@
```
     */
 }
 
-
-
+.CALEXT .weeks .eventTime {
+    display: block;
+    font-weight:normal;
+    font-size:50%;
+}
 
 .CALEXT .events {
     list-style:none;

```

When I inspect localhost:8080 and add the .CALEXT .weeks .eventTime block, the event times are shown as expected.

Doesn't seem like neither changes to custom.css or MMM-CalendarExt.css make the css addition to be effective.

Running MMM-CalendarExt version: f10031d
Running version of MagicMirror: 6db61b

pi@raspberrypi:~/MagicMirror $ git log
commit 6db61b43572d163efb6369f60238975c3e6c3efc

pi@raspberrypi:~/MagicMirror/modules/MMM-CalendarExt $ git log
commit f10031df653b8d7c587190aebed7416eedfca1a3

**Comment by dberntsson** [comment]
moved the same code to MagicMirror/css/custom.css and it works!
Doesn't seem like the custom.css file was imported (in html head-tag) in the generated source file at localhost:8080

**Comment by eouia** [comment]
I've made change the name from `custom.css` to `MMM-CalendarExt.css` to avoid conflict. `MMM-CalendarExt/custom.css` will be deprecated.
