### ISSUE TITLE
iCloud calendar not showing

### ISSUE THREAD

**Issue by KrisBird** [eouia/MMM-CalendarExt#48]
I cannot get MM to show my public iCloud calendar (have also tried with https instead of webcal):
{
  module: "MMM-CalendarExt",
  position: "middle_center",
  config: {
    calendars: [
      {
        url: "webcal://pXX-calendars.icloud.com/published/2/XXX"
      }
    ]
}
},

where as this shows up fine:
{
  module: "MMM-CalendarExt",
  position: "middle_center",
  config: {
    calendars: [
      {
        url: "https://www.fck.dk/fck.ics"
      }
    ],
 }
},

**Comment by eouia** [comment]
I need your ics url or file to anlayze. Can you send me url or file via mail? my email address is `eouia0819@gmail.com`

**Comment by KrisBird** [comment]
I apologise - didn't have any events in the calendar - so nothing showed up. No I do and it works fine. Apparently it helps writing about it :)

**Comment by eouia** [comment]
:) I'll close this issue. Have a nice day.
