### ISSUE TITLE
Toggle month shown

### ISSUE THREAD

**Issue by slodub** [eouia/MMM-CalendarExt#49]
Is there anyway to cycle forward (or backward) in month view? Would using profiles work. This could be done either with a touch screen or physical buttons...

**Comment by eouia** [comment]
Not possible, but I’m creating another new calendar module, it will have that feature. Plz wait a few days

**Comment by slodub** [comment]
Awesome!! Thanks

**Comment by eouia** [comment]
I'm building new module with another new parser and new look. I think in a few days I can release.
I'll close this issue. Have a nice day.

**Comment by slodub** [comment]
Sounds great. Please me posted of the modules name and when it will be
available. If you need a tester, I'd be down to help out where I can...
