### ISSUE TITLE
full day events shows up in every month

### ISSUE THREAD

**Issue by paljolunta** [eouia/MMM-CalendarExt#5]
I've been tinkering around with the views for a few hours and all my all day events show up in every month? I thought it was a locale/dateformat issue but no luck using different settings. I'm currently using my private gmail but the error persist even with a Swedish holiday calendar. Any thoughts?

**Comment by eouia** [comment]
Give me your config and `.ics` (if you don't mind). Then I'll try to find what is the problem.

**Comment by paljolunta** [comment]
Found the issue, related to very old birthdays added 10 years ago. When I try to replicate the issue in a new calendar everything works just fine. Thanks for quick answer thou!

**Comment by eouia** [comment]
Congrat! I'll close this issue.
