### ISSUE TITLE
Add option to ignore certain events

### ISSUE THREAD

**Issue by thomasmeeus** [eouia/MMM-CalendarExt#52]
Hi,

I would like to be able to exclude events from a calendar with a certain title like 'Birthday xx'. The default [MM calendar plugin](https://github.com/MichMich/MagicMirror/tree/master/modules/default/calendar) has the option 'excludedEvents'. Would it be hard to implement the same in this plugin?

If you can point me in the correct direction I want to try this myself, but I get a bit lost in all the javascript files as I'm not a dev :)

Thx!

**Comment by eouia** [comment]
Sorry, In `MMM-CalendarExt`, there is no option about it.
But my `MMM-CalendarExt2` has `filter` option to do that way and more.

**Comment by thomasmeeus** [comment]
Oh nice! I didn't know there was a new version out. I'll check it out. thx!
