### ISSUE TITLE
can't get a monthly view 

### ISSUE THREAD

**Issue by Goose2112** [eouia/MMM-CalendarExt#53]
hello all 
i have been trying to get a monthly view with no results, tried following the example with no luck. I am  getting a week view just fine.

John

**Comment by eouia** [comment]
Which do you mean "month" view or "monthly" view? two are different. Show me your config.

**Comment by Goose2112** [comment]
I would like the monthly layout

**Comment by eouia** [comment]
https://github.com/eouia/MMM-CalendarExt/raw/master/screencaptures/direction.jpg
This is `monthly` view.

https://github.com/eouia/MMM-CalendarExt/raw/master/screencaptures/styles_month.png
This is `month` view.

Which do you want? and show me your configuration section of `MMM-CalendarExt` in `config.js`

**Comment by Goose2112** [comment]
Would like the month view
I can't send you a pic of my config.js email is to big

**Comment by eouia** [comment]
Just copy and paste here or send via mail: eouia0819@gmail.com or Telegram: @eouia

**Comment by eouia** [comment]
This picture is not for my module. My module has name of `MMM-CalendarExt` not `MMM-Calendar` in your picture.
For configuration, Read instruction : https://github.com/eouia/MMM-CalendarExt/wiki/Configuration
Anyway, You've said you had a success for a `week` view.
The difference of `month` view  would be only adding `"month"` to `system.show` field.
```
system: {
  show: ["month", ...],
...
```

**Comment by Goose2112** [comment]
Plz check your email i sent another pic

**Comment by Goose2112** [comment]
Got it figured out thanx for the help.
Nice question i have is is it possible to big it bigger?

**Comment by eouia** [comment]
With CSS you can. But you need to know basic theory of CSS.

**Comment by eouia** [comment]
I'll close this issue, since there is no more feedback. You can reopen or post issues at any time here or newly.
Have a nice day and wish a good luck.
