### ISSUE TITLE
loading MMM - CalendarExt - Modules dissapear and need to be called back via Remote control..help?

### ISSUE THREAD

**Issue by karlfazakerley** [eouia/MMM-CalendarExt#55]

**Comment by karlfazakerley** [comment]
Hello. completely new to this...great module and what I have been looking for...however i have remote control loaded up too and I am glad I have as when i load up the Magic Mirror all the other modules dissapear and the calendar takes over...is this normal?

**Comment by eouia** [comment]
Sorry, I can't catch what you mean. CalenderExt has no feature to disappear other modules. More detail description is needed - what you did and what you expected and what you got... Screen capture or error log also could be help.

**Comment by karlfazakerley** [comment]
Hello ..so when I load up magic mirror all the modules I have appear..apart from the calendar.. this happens for a short second then they disappear and is replaced with the calendar which   Overrides the other modules and I have to manually bring the other modules into view.  Is there something I need to look at to address this ?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by eouia** [comment]
Can you take a photo with your phone and send to me? I cannot catch exactly what you mean.
My email address is eouia0819@gmail.com  or telegram account is @eouia

**Comment by eouia** [comment]
I'll close this issue because there is no feedback anymore. Anyway, I wish a good luck.
