### ISSUE TITLE
cannot see event times

### ISSUE THREAD

**Issue by flamtapgt** [eouia/MMM-CalendarExt#58]
Hi, I really like this module, but I can't get the event times to show up on the calendar. I set 'oneLineEvent' to 0 but I still only see the event name. 

This is my config: 

>                 {
                        module: 'MMM-CalendarExt',
                        position: "top_left",
                        config: {
                                system: {
                                        show: ['weeks']
                                },
                                views: {
                                        weeks: {
                                                position: 'lower_third',
                                                showWeeks: 0,
                                                counts: 4,
                                                oneLineEvent: 1
                                        }
                                },
                                calendars: [
                                        {
                                                styleName: "style1",
                                                url: "https://calendar.google.com/calendar/ical/<private>/basic.ics",
                                        }
                                ]
                        }
                },
/

Thank you for any assistance, 

flamtapgt

**Comment by eouia** [comment]
In `weeks` and `months`, I think there is not enough area to show eventTime, so I hide it.
But if you want to show it nevertheless, Add belows into your `css/custom.css`
```css
.CALEXT .tableStyle .eventTime {
    display:block;
}
```

**Comment by flamtapgt** [comment]
Thank you, this worked. 
I would like to make the font for the times a little smaller, and the font for the event names a little bigger. Can you tell me where I would find the code to do this?

**Comment by eouia** [comment]
modify your `css/custom.css` to something like this. 
```css
.CALEXT .tableStyle .eventTime {
  display:block;
  font-size: 10px;
}

.CALEXT .tableStyle .eventContent {
  font-size:13px;
}
```
Adjust the value as your desire. Anyway, you might need to adjust other propertiy-values also (like margin, padding or line-height, etc)  See `MMM-CalendarExt.css` and find what you need, then redefine it in `css/custom.css`

**Comment by flamtapgt** [comment]
Thanks!
