### ISSUE TITLE
Limiting upcoming events to the end of the day

### ISSUE THREAD

**Issue by GattoJohnny** [eouia/MMM-CalendarExt#59]
Is there a way to limit displaying the upcoming events from the current time to the end of the day?
Either hiding past events from '_daily_' view, or limiting '_upcoming_' view to EOD may help me out.

**Comment by eouia** [comment]
Somewhat obvious question.(sorry my poor English)
Anyway, each view can limit events by “limit:NUMBER”.
Especially limit till eod, you need to adjust “calendar.maxDays” to 1, then use it in view.

**Comment by eouia** [comment]
If you want more than  “hiding all past events from view” or “limit number of events”, consider use “MMM-CalendarExt2”. It has more poweful configuration(but needs basic js skill)

**Comment by GattoJohnny** [comment]
I was aware of limit:NUMBER but it was not the solution. However, maxDays:1 did the trick! 
Thanks for the excellent and prompt assistance. 
As long as CalendarExt serves my needs I'll be okay with that.  Maybe later I'll give Ext2 a shot. Till then I wish you all the best for the development.

**Comment by eouia** [comment]
Nice to hear it. I’ll close this.
