### ISSUE TITLE
Current events shown at the wrong time

### ISSUE THREAD

**Issue by kallioaleksi** [eouia/MMM-CalendarExt#61]
I live in Finland, which has the timezone GMT+2/+3 depending on the DST. If I have an event at, let's say, 16:00 - 17:00, it shows the correct time in the calendar, but it's moved to the current section at 19:00 - 20:00, as if it's GMT+0.

**Comment by eouia** [comment]
can i get your ics url to examine?

**Comment by kallioaleksi** [comment]
Sorry, that was due to my Pi having the wrong timezone. Somehow the clock on the screen had it correct. I changed the timezone and now it works!

**Comment by eouia** [comment]
Nice to hear it. Have a great day.
