### ISSUE TITLE
Show only the week I want

### ISSUE THREAD

**Issue by Stant0n** [eouia/MMM-CalendarExt#62]
I would like to show only one week, next month. Is there a way of doing that?

**Comment by eouia** [comment]
Sorry, I cannot exactly catch your words. It means you want to show the 1st weeks of May? (Case; Today is 23rd April) And which `view` did you mentioned?

**Comment by Stant0n** [comment]
I only want to show the last week in May

**Comment by eouia** [comment]
If you mean `ALWAYS showing the last 7 days of May` regardless which day is today, it couldn't be possible without modifying configuration weekly again on start of every week. Sorry, I haven't imagine that usage ever.

**Comment by Stant0n** [comment]
Ok. Thank you. There’s a convention that week and I’d like to show just the events for those days. 

I appreciate you getting back to me. 

Brian
