### ISSUE TITLE
All day on same line

### ISSUE THREAD

**Issue by qwertyjon** [eouia/MMM-CalendarExt#63]
Is there a way to have an all-day event that spreads over multiple days be on the same line for all the days?

![2019-06-11 (1)](https://user-images.githubusercontent.com/42122953/59254354-ed0a5000-8c27-11e9-93ea-3cb08a068b1e.png)

**Comment by eouia** [comment]
not so easy way. I think you'd better to use `MMM-CalendarExt2` instead. It has that feature.

**Comment by qwertyjon** [comment]
Thanks
