### ISSUE TITLE
only show Monday thru Friday slots

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt#65]
I would like to only show the M-F slots for the current and following week like in the image and not Saturday and Sunday. How can i accomplish this? What setting do i need to change?

![calendar](https://user-images.githubusercontent.com/41309095/62243988-51799e00-b393-11e9-91b1-981c00d4fe74.jpg)

**Comment by eouia** [comment]
Not supported. You can use `MMM-CalendarExt2`, it has that feature.

**Comment by ingo916** [comment]
Thanks, I will try that. Do I configure it the same way as the current version?

**Comment by eouia** [comment]
Not so same (The structure and concepts are entirely changed), but I believe you can do it. 
Read the documents.
