### ISSUE TITLE
I can not get MMM-CalendarExt to run again.

### ISSUE THREAD

**Issue by Plainbroke** [eouia/MMM-CalendarExt#67]
Here is my config in config.js please help when you can.
I want to run it in month or monthly configuration I am using a 32" TV/Monitor as my display.
Just did a fresh install from loading Debian Buster to fresh auto load of MagicMirror.
Everything else works fine but can't figure out what I am doing wroing in the config.js, passes npm run config:check and MagicMirror is showiing default calendar, clock, MMM-MyWeather
randomquotes, daily quotes, MMM-ATM, MMM-Globe and MMM-NASA, all running on most of the screen as single pages using MMM-Carousel they run great. So you can see why I am asking for help.   All that works great together.

**Comment by eouia** [comment]
config of MMM-CalendarExt itself has no problem. But with MMM-Carousel, it should be the first page or all page.
(I didn't consider MMM-Carousel).

Or you can use `MMM-CalendarExt2` instead.

**Comment by Plainbroke** [comment]
Will look into the CalendarExt2 might be more what I am looking for anyways.
Thank you for the Information so quickly.
I am new to MM but am having a lot of fun with this little project.

**Comment by Plainbroke** [comment]
Cant get either to work for me.   The config.js and custom.css are really confusing for CX2.

Jeff Burdick
