### ISSUE TITLE
How to Update?

### ISSUE THREAD

**Issue by nickymac12** [eouia/MMM-CalendarExt#69]
Hi,

May be a silly question, but how do you update the module? I used git pull && npm install to update MagicMirror but the MMM-CalendarExt module still tells me that there is an update available. Is there another way to do an update?

**Comment by eouia** [comment]
for updating of common MagicMirror modules,
1) go to the target module directory (`cd ~/MagicMirror/modules/MMM-CalendarExt`)
2) do `git pull`
3) if the module has `package.json` and `node_modules` in its directory, do `npm install`
4) Or ask the creator of that module.
