### ISSUE TITLE
TypeError: exdate[name].toISOString is not a function with Office 365 ics 

### ISSUE THREAD

**Issue by tars01** [eouia/MMM-CalendarExt#70]
I see this was raised as issue #46 but no resolution. I am facing the same issue and wondering if there is a resolution or workaround to this? I have this working without any issues when pointing to a Google calendar ics file but when I try and point it to Office 365 calendar I am having the issue with loading the ics file:

 'TypeError: exdate[name].toISOString is not a function'  

Please see output from pm2 log:

 /home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1161:10)
0|mm       |     at Request.emit (events.js:182:13)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:273:13)
0|mm       | TypeError: exdate[name].toISOString is not a function <----------
0|mm       |     at Object.EXDATE (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/ical.js:200:35)
0|mm       |     at Object.handleObject (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/ical.js:379:41)
0|mm       |     at Object.parseICS (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/ical.js:420:20)
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-CalendarExt/vendor/ical.js/node-ical.js:18:23)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
0|mm       |     at Request.emit (events.js:182:13)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1161:10)
0|mm       |     at Request.emit (events.js:182:13)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:273:13)

**Comment by eouia** [comment]
Can you share the .ics for me to test? eouia0819@gmail.com

**Comment by tars01** [comment]
It's confidential unfortunately, is there sections of it I can pull out to help identify the issue?

**Comment by eouia** [comment]
Sorry, I have no idea about it.

**Comment by tars01** [comment]
OK thanks. I am trying to clean out all the confidential data in the ics file so I can send to you.

Thanks

________________________________
