### ISSUE TITLE
.ICS calendars from local file as variable

### ISSUE THREAD

**Issue by SpyEye70** [eouia/MMM-CalendarExt#71]
Hey.
Is it possible to put the links for the .ics calendars in a local file, and then load them into CalendarExt as variables?
Dome of my calendars change links 2 times a test, so it would be easier to just opload a new file, instead of changing the config file.
/Morten

**Comment by eouia** [comment]
Hmmm. not tested, but if you put that ical file into the MMM-CalendarExt directory,
you could access it as `https://localhost:8080/modules/MMM-CalendarExt/myTestCalendar.ics`.

**Comment by SpyEye70** [comment]
Good idea.That will work too.Thank you😊-------- Oprindelig meddelelse --------Emne: Re: [eouia/MMM-CalendarExt] .ICS calendars from local file as variable (#71)Fra: Seongnoh Sean Yi Til: eouia/MMM-CalendarExt CC: SpyEye70 ,Author Hmmm. not tested, but if you put that ical file into the MMM-CalendarExt directory,
you could access it as https://localhost:8080/modules/MMM-CalendarExt/myTestCalendar.ics.
