### ISSUE TITLE
Incorrect recurrence from ical?

### ISSUE THREAD

**Issue by mabahj** [eouia/MMM-CalendarExt#73]
Great plugin! Thank you very much for making this! I'd really like to use this, but unfortunately, in my very fresh installation, CalendarExt shows recurring events at wrong dates. The normal MagicMirror calendar module (as well as Outlook and Android calendar) shows them correctly. I've reduced my ical to one of these recurring event only.

* CalendarExt: *Incorrect:* First event is Sunday, then recurring Mondays. 
* MagicMirror default calendar: *Correct:* First event is Monday, then recurring Mondays.

![MMM-CalendarExt-incorrect_recurrence](https://user-images.githubusercontent.com/11989549/67623455-a3f91800-f825-11e9-9386-4af211bfe269.png)

The ical is reduced to only contain one event, running from a local web server for debugging:

> BEGIN:VCALENDAR
> PRODID:-//Google Inc//Google Calendar 70.9054//EN
> VERSION:2.0
> CALSCALE:GREGORIAN
> METHOD:PUBLISH
> X-WR-CALNAME:Family
> X-WR-TIMEZONE:Europe/Oslo
> BEGIN:VTIMEZONE
> TZID:Etc/UTC
> X-LIC-LOCATION:Etc/UTC
> BEGIN:STANDARD
> TZOFFSETFROM:+0000
> TZOFFSETTO:+0000
> TZNAME:GMT
> DTSTART:19700101T000000
> END:STANDARD
> END:VTIMEZONE
> BEGIN:VTIMEZONE
> TZID:Europe/Oslo
> X-LIC-LOCATION:Europe/Oslo
> BEGIN:DAYLIGHT
> TZOFFSETFROM:+0100
> TZOFFSETTO:+0200
> TZNAME:CEST
> DTSTART:19700329T020000
> RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
> END:DAYLIGHT
> BEGIN:STANDARD
> TZOFFSETFROM:+0200
> TZOFFSETTO:+0100
> TZNAME:CET
> DTSTART:19701025T030000
> RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
> END:STANDARD
> END:VTIMEZONE
> BEGIN:VEVENT
> DTSTART;TZID=Europe/Oslo:20190923T183000
> DTEND;TZID=Europe/Oslo:20190923T190000
> RRULE:FREQ=WEEKLY;WKST=TU
> EXDATE;TZID=Europe/Oslo:20190930T183000
> DTSTAMP:20191026T114331Z
> UID:70o6co9pcdi62bb275h66b9k69hm4b9oc9gjeb9m6ph3icpm6hgj6cr4cc@google.com
> CREATED:20190923T081824Z
> DESCRIPTION:
> LAST-MODIFIED:20190923T081824Z
> LOCATION:
> SEQUENCE:0
> STATUS:CONFIRMED
> SUMMARY:My recurring event
> TRANSP:OPAQUE
> END:VEVENT
> END:VCALENDAR

**Comment by eouia** [comment]
It seems `SummerTime` bug on my parser. Hmmm. I'll inspect how to fix it.

**Comment by eouia** [comment]
Anyway, You can consider  to use `MMM-CalendarExt2` instead. It is using a new different parser from `MMM-CalendarExt`.

![image](https://user-images.githubusercontent.com/1720610/67634500-28e34080-f8bd-11e9-9192-dac01246b01f.png)

**Comment by eouia** [comment]
I fixed. update module and try to test it again

![image](https://user-images.githubusercontent.com/1720610/67636980-5be5fe00-f8d6-11e9-83eb-d456c84a719d.png)

**Comment by mabahj** [comment]
Great, that fixed it! Thank you very much! And thanks again for sharing your project!

**Comment by joberbr** [comment]
Hello,
I am getting a similar issue even with the update. All of my recurring events after 5 PM local time are being moved to the previous day.
Thanks
Jeremy

**Comment by eouia** [comment]
@joberbr 
Without real ical data, I have nothing to say about it. I'm not clairvoyance. :D
And you'd better write a post as a new issue.
