### ISSUE TITLE
Recurring items not displaying correct day

### ISSUE THREAD

**Issue by joberbr** [eouia/MMM-CalendarExt#74]
Reoccurring items after 5 pm local time are appearing on the previous day. Here is an example of one such event:

SUMMARY:Example Event
DTSTART;TZID=America/Phoenix:20190807T180000
DTEND;TZID=America/Phoenix:20190807T190000
DTSTAMP:20191028T235131Z
UID:43e73f1d-b4f2-4fae-be96-b1b4df03f7da
SEQUENCE:4603
RRULE:FREQ=WEEKLY;BYDAY=WE
EXDATE;TZID=America/Phoenix:20190918T180000
EXDATE;TZID=America/Phoenix:20191002T180000
EXDATE;TZID=America/Phoenix:20191016T180000
EXDATE;TZID=America/Phoenix:20191127T180000
END:VEVENT
BEGIN:VEVENT

**Comment by eouia** [comment]
Full ical data is needed.
There should be more than `VEVENT` data, like `VTIMEZONE`, `DAYLIGHT`, ... Especially I doubt your `timezone` data of event is not matched your current timezone of system.
Which timezone are you living in? Are you living in `America/Phoenix`?

**Comment by joberbr** [comment]
I am in living in Phoenix. The current time zone is set on the RPI. Here is the full iCal data for one recurring event.

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Cozi Group Inc//Cozi Calendar//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-PUBLISHED-TTL:PT10M
X-WR-CALDESC:Family Calendar. Generated by Cozi\, http://www.coz
 i.com/
X-WR-CALNAME:Family Calendar
X-WR-RELCALID:43d3ab49-6c7a-4f6d-963b-c1e2f442f3fa
X-WR-TIMEZONE:America/Phoenix
BEGIN:VTIMEZONE
TZID:America/Phoenix
BEGIN:STANDARD
DTSTART:20000101T000000
RRULE:FREQ=YEARLY;BYMONTH=1
TZNAME:MST
TZOFFSETFROM:-0700
TZOFFSETTO:-0700
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:My Recurring Event
DTSTART;TZID=America/Phoenix:20190807T180000
DTEND;TZID=America/Phoenix:20190807T190000
DTSTAMP:20191028T235131Z
UID:43e73f1d-b4f2-4fae-be96-b1b4df03f7da
SEQUENCE:4603
RRULE:FREQ=WEEKLY;BYDAY=WE
EXDATE;TZID=America/Phoenix:20190918T180000
EXDATE;TZID=America/Phoenix:20191002T180000
EXDATE;TZID=America/Phoenix:20191016T180000
EXDATE;TZID=America/Phoenix:20191127T180000
END:VEVENT
END:VCALENDAR

**Comment by g3zar** [comment]
I am having this same issue. When I create a recurring event via Google Calendar, it shows on the wrong day in MM. When I create the same recurring event using the iOS calendar app (also pointed at my Google Calendar) it displays on the correct day in MM. The difference between the two ics entries is the RRULE line. 

Event created in Google Calendar (which shows on the wrong day in MM) shows:

RRULE:FREQ=WEEKLY;BYDAY=TH

Event created in iOS (which shows on the correct day in MM) shows:

RRULE:FREQ=WEEKLY;INTERVAL=2

Other than this, the two ics entries look identical. Google's interface doesn't seem to give me the option of specifying a weekly repeat without selecting a specific weekday (in this case, Thursday). Hope this helps!

**Comment by eouia** [comment]
Hard to fix this issue due to old parser. Consider to use MMM-CalendarExt2
