### ISSUE TITLE
Deleted one event from recurring chain of events, but still show

### ISSUE THREAD

**Issue by dberntsson** [eouia/MMM-CalendarExt#75]
I have a Google calendar shown on my MagicMirror2 with your module.

I have a recurring event every monday.
One of these events i removed (only one), but is still remains visible on the MM.
This has worked before...

**Comment by eouia** [comment]
Give me your ical file or url to inspect. without it, I cannot tell you anything.

**Comment by dberntsson** [comment]
Even though EXDATE, the events are still shown
EXDATE;TZID=Europe/Stockholm:20191101T072500
EXDATE;TZID=Europe/Stockholm:20191031T072500
EXDATE;TZID=Europe/Stockholm:20191030T072500
EXDATE;TZID=Europe/Stockholm:20191029T072500
EXDATE;TZID=Europe/Stockholm:20191028T072500


Attaching the vital parts of the ics:

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Hilda
X-WR-TIMEZONE:Europe/Stockholm
BEGIN:VTIMEZONE
TZID:Etc/UTC
X-LIC-LOCATION:Etc/UTC
BEGIN:STANDARD
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Stockholm
X-LIC-LOCATION:Europe/Stockholm
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE

BEGIN:VEVENT
DTSTART;TZID=Europe/Stockholm:20190917T072500
DTEND;TZID=Europe/Stockholm:20190917T163000
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20191222T225959Z;INTERVAL=2;BYDAY=FR,MO,TH,
 TU,WE
EXDATE;TZID=Europe/Stockholm:20191101T072500
EXDATE;TZID=Europe/Stockholm:20191031T072500
EXDATE;TZID=Europe/Stockholm:20191030T072500
EXDATE;TZID=Europe/Stockholm:20191029T072500
EXDATE;TZID=Europe/Stockholm:20191028T072500
DTSTAMP:20191031T135413Z
UID:0nn28smv11q1j9t6pdfmi6rvah_R20190917T052500@google.com
CREATED:20190817T201108Z
DESCRIPTION:
LAST-MODIFIED:20190917T201335Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Fritids
TRANSP:OPAQUE
END:VEVENT

END:VCALENDAR

**Comment by eouia** [comment]
You are right. I think my parser couldn't handle `EXDATE` rightly.
Anyway, I'm not supporting this `MMM-CalendarExt` any more because it is using a too old parser. (Basically it's origin is same with parser of default calendar module, But too many hotfixes are needed to maintain)
So I made a new one with a better/new parser. In MMM-CalendarExt2 your events are shown properly.

![image](https://user-images.githubusercontent.com/1720610/67957909-98776980-fbf6-11e9-91eb-dd9f81f246ff.png)
