### ISSUE TITLE
All Day events are shown the next day

### ISSUE THREAD

**Issue by Obelix74Git** [eouia/MMM-CalendarExt#77]
I got several calendars with all-day events. Since the fix for daylight saving about a month ago, this problem occurs. For example December 5th is shown on the 6th.

One of my calendars is https://www.thunderbird.net/media/caldata/DutchHolidays.ics.

**Comment by eouia** [comment]
Can I see your configuration also?

**Comment by Obelix74Git** [comment]
Here is the Calendar config, or do you need the full config?

		{
			module : "MMM-CalendarExt",
			disabled : false,
			position : "bottom_bar",
			config : {
				system : {
					show : ["current","upcoming","weeks"], // daily, weekly, monthly, month, weeks, upcoming, current
					locale : "nl-NL",
					showEmptyView : 1,
				},
				defaultView : {
					dateFormat : "D MMM",
				},
				views : {
					weeks : {
						position : "bottom_bar",
						showWeeks : 1,
						weeksTitle : "week",
						weeksFormat : "w",
						weekdayFormat : "dddd",
						titleFormat : "D MMM",
						overTitleFormat : "D MMMM",
						counts : 3, // Hoeveel weken moeten er getoond worden
						//oneLineEvent : 1,
						ellipsis : 70, // Hoeveel karakters worden er per afspraak getoond.
						//overflowRolling : 1,
						//overflowHeight : 160,
						//overflowDuration : 4,
					},
					current : {
						position : "top_left",
						title : "Nu bezig",
						useRelative : 0,
						titleFormat : "D MMM",
						fullDayEventDateFormat : "D MMM",
					},
					upcoming : {
						position : "top_left",
						title : "Binnenkort",
						titleFormat : "D MMM",
						fullDayEventDateFormat : "D MMM",
						useRelative : 0,
						limit : 6,
                                                ellipsis : 40, // Hoeveel karakters worden er per afspraak getoond.
					},
				},
				defaultCalendar : {
					maxEntries:50, // How many events will be fetched from this calendar,
					maxDays:40, // .. until this.
					interval : 36000000, // (milliseconds) Interval for fetching schedule.
				},
				calendars :[
					{
						name : "Feestdagen",
						url : "https://www.thunderbird.net/media/caldata/DutchHolidays.ics",
						symbol : "nl@fi",
						styleName : "style20",
						//maxEntries : 6,
						//maxDays : 40,
						//interval : 30*24*60*60*1000, // 1000ms * 60 sec * 60 min * 24 uur * 30 dagen (1 keer per maand dus)
					},
				],
			},
		},

**Comment by Obelix74Git** [comment]
Why is this clossed? 
I didn't do that......

Some extra information about the problem.

The problem occurs when you have an all-day event that is repeated every year.
An all-day event that is not repeated doesn’t have the problem.
Does that helps a bit in finding the problem.

**Comment by eouia** [comment]
Hmmm. you've closed this issue by yourself so I thought you solved this issue;
![image](https://user-images.githubusercontent.com/1720610/69914557-01e0d700-1446-11ea-9191-409ebc10ffbf.png)
Anyway,

<img width="1127" alt="123" src="https://user-images.githubusercontent.com/1720610/69914746-04443080-1448-11ea-89ac-5862b7b622b1.png">

`MMM-CalendarExt` is using the same parser with `default calendar module` of MichMich, but the parser is not so good. It has plenty of bugs in ther parser. That is why I created a new module `MMM-CalendarExt2`. CALEXT2 is using a newer and better parser. 

My suggestion is, to use `MMM-CalendarExt2`. It's more powerful than my alt.

**Comment by Obelix74Git** [comment]
Thanks for sorting it out.
I'm going to install CALEXT2 .
