### ISSUE TITLE
Decrease/remove margins

### ISSUE THREAD

**Issue by smartroad** [eouia/MMM-CalendarExt#80]
I was wondering if it is possibole to reduce the size of the left, right and bottom margins? The blue areas in this photo?

https://i.ibb.co/nCM7XqM/20200329-184330.jpg

**Comment by eouia** [comment]
Which region you've put the view? Usually, the width depends on the region size.

**Comment by smartroad** [comment]
bottom bar - although it doesn't seem to matter what I put into `position:` it is always at the bottom of the screen

**Comment by eouia** [comment]
First, put this into your `css/custom.css`

```css
.CALEXT .tableStyle {
  max-width: inherit;
}
```

Second, where did you put `position`? it means not module's position. Each view could have it's own position, so you have to put `position` in `view` section.
![image](https://user-images.githubusercontent.com/1720610/77945653-4465d380-72c1-11ea-8aee-5afe69b54b33.png)
