### ISSUE TITLE
Mmm-calendarext one day difference between ics file and MagicMirror display

### ISSUE THREAD

**Issue by Doudy** [eouia/MMM-CalendarExt#84]
hello,
I have at mmm-calendarext one day difference between outlook-ouwncloud.ics file and MagicMirror display only for anniversary

outlook-owncloud.ics:
[https://framapic.org/bFIR9UtixB1o/VlJmx9xbEqJc.PNG](url)

mmm-calendarext:
[https://framapic.org/lsKZMrDbtCQa/CzWnRyCKXYQG.PNG](url)

At outlook.ics i have anniversary jean-Pol friday 03/04 but at calendarext it is 04/04
At outlook.ics i have anniversary Gilles sunday 05/04 but at calendarext it is 06/04
At outlook.ics i have anniversary Nathalie sunday 05/04 but at calendarext it is 06/04
etc…

It is only birthdays that are not correct.
The rest is good.

An idea ?
See also : [https://forum.magicmirror.builders/topic/12492/mmm-calendarext-one-day-difference-between-ics-file-and-magicmirror-display/2](url)

**Comment by eouia** [comment]
This module is somewhat old. The 3rd party vendor parser(which is originally same with that of default calendar module) has some annoying bug about timezone and daylight-save. 
If possible, use `MMM-CalendarExt2`. it's better. And I don't support this legacy module any more.

**Comment by Doudy** [comment]
Thank you for the quick reply.
I test immediately MMM-CalendarExt2
